### ISSUE TITLE
Get all outgoing SMS details in one request

### ISSUE THREAD

**Issue by Inglebard** [ovh/php-ovh#134]
Hi,

This question is similar to #132 but for outgoing SMS details.

If I follow the api doc, "/sms/{serviceName}/outgoing" return a list of IDs.
Then I need to request "/sms/{serviceName}/outgoing/{id}" to have the details. This is pretty slow when there are a lot of IDs.

On the OVH Manager, the web interface send to "https://www.ovhtelecom.fr/engine/apiv6/sms/{serviceID}/outgoing?batchID={batchID}&creationDatetime.from={dateFrom}&creationDatetime.to={dateTo}" but instead of have a list of IDs, it return a list with all the details which is faster.

Is possible to do the same thing with the api ?

**Comment by a-beudin** [comment]
Hello,

The [/sms/outgoing](https://api.ovh.com/console-preview/?section=%2Fsms&branch=v1#get-/sms/-serviceName-/outgoing) endpoint always returns a list of IDs, and the only way to get all sms details is to get one by one by ID.

The OVH manager probably (I could not try it) does the same thing under the hood.

**Comment by rbeuque74** [comment]
Hello,

Thanks for your issue.
As @a-beudin said, the endpoint `/sms/:serviceId/outgoing` is returning a list of IDs. You will have to iterate over the list to retrieve all the values.
The OVH Manager has indeed an under the hood mecanism to fetch all the records at the same time, but this is not possible using api.ovh.com/v1. We will rewrite a part of our APIs in the future to have a return that always be a list of objects, instead of list of ids.

If you have any further questions regarding the API itself, and not regarding the PHP wrapper for our API, I would ask you to join the API community mailing-list, where we are addressing our customers questions: api@ml.ovh.net (subscription by sending an email to api-subscribe@ml.ovh.net and follow the instructions).

I will close this issue at it is not related to php-ovh wrapper.
