### ISSUE TITLE
Set ssh key on VPS order

### ISSUE THREAD

**Issue by jo66** [ovh/php-ovh#91]
It's no option about ssh key when ordering VPS, so no way to connect it from script after order (see #90).
Seems the only workaround is to reinstall VPS before use with `/vps/{serviceName}/reinstall`.
If ssh key can be set on reinstall, I guess it should be possible to set it when ordering VPS, right?

**Comment by Alkorin** [comment]
That's exactly what I'm asking to VPS developers ;)

**Comment by rbeuque74** [comment]
Hey!
@jo66: Could we continue this discussion on the mailing-list instead of creating an issue on this repository.
This feature lack is not directly linked to the development of this PHP wrapper, but a global API development. Conversation would have a better visibility on the mailing-list, where VPS team developers could exchange with you, instead of this repository where we only maintain the php wrapper.

Is that ok for you ? Can we close this one ?
Thanks, Romain

**Comment by jo66** [comment]
@rbeuque74 you are right, I close.
